import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppLayout from '~/modules/app-layout'
import '~/modules/global-styles/variables.css'
import '~/modules/global-styles/reset.css'
// import '~/modules/global-styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <AppLayout>
        {children}
        </AppLayout>
        </body>
    </html>
  )
}
